version: "3.12.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map port 5000 of the container to port 5000 on the host
    volumes:
      - .:/app  # Mount local project directory to /app in the container
    environment:
      - FLASK_ENV=development  # Example environment variable
      - MONGO_URI=mongodb://mongo:27017/users_db
    depends_on:
      - mongo


  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: